name: multilaser
channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - anaconda::pyqt
  - pyserial[version='>=3.5']
  - python[version='>=3.7']
  - pyinstaller
  - pyusb
  - ca-certificates
  - openssl
  - ipython
  - cython
  - termcolor
  - pyvisa
  - pyvisa-py
  - psutil
