name: multilaser
channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  # - pyqt6
  - pyserial[version='>=3.5']
  - python[version='>=3.7']
  - pyinstaller
  - pyusb
  - ca-certificates
  - openssl
  - ipython
  - cython
  - termcolor
  - pyvisa
  - pyvisa-py
  - psutil
prefix: /Users/chrisbetters/miniforge3/envs/multilaser
